version: '3.8'
services:
  jwt-auth:
    build: jwt-auth-server/.
    image: jwt_auth_server
    container_name: jwt_auth_server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:8081"
      - "9081:9081"
    depends_on:
      - jwt-auth-db
    environment:
      - JWT_SPRING_DATASOURCE_URL=jdbc:postgresql://jwt-auth-db:5432/jwtserver
      - JWT_DB_USER=jwtserveradmin
      - JWT_DB_PASSWORD=jwtserveradmin
      - JWT_SECRET_ACCESS=YW5nYXJrYWh1YnNlY3JldGtleWZvcmF1dGhvcml6YXRpb25zZXJ2ZXI=
      - JWT_SECRET_REFRESH=YW5nYXJrYWh1YnJlZnJlc2hrZXlmb3JhdXRob3JpemF0aW9uc2VydmVy
      - JWT_AUTH_SERVER_PORT=8081

  jwt-auth-db:
    image: postgres:14-alpine
    container_name: jwt_auth_db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - jwt-postgresql-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=jwtserver
      - POSTGRES_USER=jwtserveradmin
      - POSTGRES_PASSWORD=jwtserveradmin

  manager:
    build: manager/.
    image: manager
    container_name: manager
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "9080:9080"
    depends_on:
      - jwt-auth
      - jwt-auth-db
      - manager-db
    environment:
      - MANAGER_SPRING_R2DBC_URL=r2dbc:pool:postgres://manager-db:5432/managerdb
      - MANAGER_DB_USER=managerdbadmin
      - MANAGER_DB_PASSWORD=managerdbadmin
      - MANAGER_SERVER_PORT=8080
      - JWT_SECRET_ACCESS=YW5nYXJrYWh1YnNlY3JldGtleWZvcmF1dGhvcml6YXRpb25zZXJ2ZXI=

  manager-db:
    image: postgres:14-alpine
    container_name: manager_db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - manager-postgresql-data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=managerdb
      - POSTGRES_USER=managerdbadmin
      - POSTGRES_PASSWORD=managerdbadmin

volumes:
  jwt-postgresql-data:
  manager-postgresql-data: