drop table if exists executors_tasks;
drop table if exists comments;
drop table if exists tasks;
drop table if exists users;

create table if not exists users
(
    id bigint primary key,
    login varchar(32) not null unique
);
create table if not exists tasks
(
    id bigint generated by default as identity primary key,
    author_id bigint not null references users(id) on delete cascade ,
    title varchar(32) not null,
    description varchar(1024) not null,
    status varchar(16) not null,
    priority varchar(16) not null
);
create table if not exists executors_tasks
(
    executor_id bigint not null references users(id) on delete cascade ,
    task_id bigint not null references tasks(id) on DELETE cascade,
    unique (executor_id, task_id)
);
create table if not exists comments
(
    id bigint generated by default as identity primary key ,
    author_id bigint not null references users(id) on delete cascade ,
    task_id bigint not null references tasks(id) on delete cascade ,
    content varchar(1024) not null
);